### ISSUE TITLE
Hard-coded numbers in synthesis.py

### ISSUE THREAD

**Issue by LeviBarnes** [SKA-ScienceDataProcessor/crocodile#2]
Calls to wkernelaf in synthesis.py contain hard-coded numbes 257 and 15. Those would be better understood if they had text names. Also, should those be adjustable in any way?

**Comment by bnikolic** [comment]
I will try to have a look at this. However, in case I don't Vlad could you please put it onto the the list of things to look into?

**Comment by vlad7235** [comment]
Yes, I'll have a look.

**Comment by bnikolic** [comment]
I've removed the hard coded values and replaced them with parameters. The choice of parameters is illustrated in file doc/wkernel.rstw in commit 
22ec7f538e8aefe2cc1ff672114de81d517ac586

**Comment by bnikolic** [comment]
I think that closes it for now. We should have a function which computes suitable size of the far-field given maximum w value in a dataset
